class Theme:
    def __init__(self):
        self.current = "dark"
        self.COLORS = {
            "dark": {
                "bg": "#0b0d11",
                "panel": "#111826",
                "card": "#0f1624",
                "fg": "#e8f0ff",
                "muted": "#8ea6c8",
                "border": "#1d2b3f",
                "accent": "#4cc2ff",
                "accent_hover": "#6fd0ff",
                "accent_dark": "#2aa4f2",
                "button_bg": "#16324a",
                "button_fg": "#4cc2ff",
                "button_border": "#2b4a6b",
                "button_hover": "#f4fbff",
                "button_pressed": "#0f2a42",
                "input_bg": "#0c1420",
                "input_fg": "#e8f0ff",
                "input_border": "#2b4a6b",
                "input_focus": "#4cc2ff",
                "tree_bg": "#0d1422",
                "tree_alt": "#0f1828",
                "tree_fg": "#e8f0ff",
                "select_bg": "#1d3b5a",
                "select_fg": "#4cc2ff",
            },
            "for_divas": {
                "bg": "#ffe8f3",
                "panel": "#ffd4ea",
                "card": "#fff6fb",
                "fg": "#6f1d4f",
                "muted": "#9a4c79",
                "border": "#f3a6ce",
                "accent": "#ff5aa5",
                "accent_hover": "#ff7cb8",
                "accent_dark": "#e64595",
                "button_bg": "#ff8dc7",
                "button_fg": "#fff7fc",
                "button_border": "#f06db3",
                "button_hover": "#ffb2d8",
                "button_pressed": "#e95ea7",
                "input_bg": "#fff4fa",
                "input_fg": "#6f1d4f",
                "input_border": "#f3a6ce",
                "input_focus": "#ff5aa5",
                "tree_bg": "#fff8fc",
                "tree_alt": "#ffeef7",
                "tree_fg": "#6f1d4f",
                "select_bg": "#ff9dce",
                "select_fg": "#fff7fc",
            },
        }


theme = Theme()
